// Generated by scripts/gen-db-types.mjs from supabase/migrations. Do not edit.
// Regenerate with `npm run db:types` after adding a migration.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      analytics_erasure_jobs: {
        Row: {
          attempts: number
          created_at: string
          distinct_id: string
          last_error: string | null
          status: string
          tracking_id: string | null
          updated_at: string
        }
        Insert: {
          attempts?: number
          created_at?: string
          distinct_id: string
          last_error?: string | null
          status?: string
          tracking_id?: string | null
          updated_at?: string
        }
        Update: {
          attempts?: number
          created_at?: string
          distinct_id?: string
          last_error?: string | null
          status?: string
          tracking_id?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      apps: {
        Row: {
          client_name: string | null
          created_at: string
          id: string
          name: string
          orientation: string
          slug: string
          updated_at: string
          workspace_id: string
        }
        Insert: {
          client_name?: string | null
          created_at?: string
          id?: string
          name: string
          orientation?: string
          slug: string
          updated_at?: string
          workspace_id: string
        }
        Update: {
          client_name?: string | null
          created_at?: string
          id?: string
          name?: string
          orientation?: string
          slug?: string
          updated_at?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "apps_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      asc_connections: {
        Row: {
          auth_tag: string
          created_at: string
          created_by: string
          encrypted_private_key: string
          id: string
          issuer_id: string
          iv: string
          key_id: string
          last_verified_at: string | null
          workspace_id: string
        }
        Insert: {
          auth_tag: string
          created_at?: string
          created_by: string
          encrypted_private_key: string
          id?: string
          issuer_id: string
          iv: string
          key_id: string
          last_verified_at?: string | null
          workspace_id: string
        }
        Update: {
          auth_tag?: string
          created_at?: string
          created_by?: string
          encrypted_private_key?: string
          id?: string
          issuer_id?: string
          iv?: string
          key_id?: string
          last_verified_at?: string | null
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "asc_connections_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: true
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      checkout_attempts: {
        Row: {
          attempt_id: string
          expires_at: string
          kind: string
          return_path: string
          session_id: string | null
          workspace_id: string
        }
        Insert: {
          attempt_id?: string
          expires_at?: string
          kind: string
          return_path: string
          session_id?: string | null
          workspace_id: string
        }
        Update: {
          attempt_id?: string
          expires_at?: string
          kind?: string
          return_path?: string
          session_id?: string | null
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "checkout_attempts_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: true
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      consent_events: {
        Row: {
          accepted: boolean
          created_at: string
          id: string
          kind: string
          policy_version: string
          user_id: string
        }
        Insert: {
          accepted: boolean
          created_at?: string
          id?: string
          kind: string
          policy_version: string
          user_id: string
        }
        Update: {
          accepted?: boolean
          created_at?: string
          id?: string
          kind?: string
          policy_version?: string
          user_id?: string
        }
        Relationships: []
      }
      daily_export_counts: {
        Row: {
          count: number
          day: string
          workspace_id: string
        }
        Insert: {
          count?: number
          day: string
          workspace_id: string
        }
        Update: {
          count?: number
          day?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "daily_export_counts_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      dsar_requests: {
        Row: {
          created_at: string
          id: string
          payload: Json | null
          processed_at: string | null
          status: string
          type: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          payload?: Json | null
          processed_at?: string | null
          status?: string
          type: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          payload?: Json | null
          processed_at?: string | null
          status?: string
          type?: string
          user_id?: string
        }
        Relationships: []
      }
      export_reservations: {
        Row: {
          created_at: string
          id: string
          kind: string
          quota_day: string
          state: string
          user_id: string
          workspace_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          kind: string
          quota_day?: string
          state?: string
          user_id: string
          workspace_id: string
        }
        Update: {
          created_at?: string
          id?: string
          kind?: string
          quota_day?: string
          state?: string
          user_id?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "export_reservations_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      export_sets: {
        Row: {
          app_id: string | null
          background_mode: string
          created_at: string
          created_by: string
          filename: string
          fit_mode: string
          format: string
          id: string
          image_count: number
          include_69: boolean
          orientation: string
          storage_path: string | null
          workspace_id: string
        }
        Insert: {
          app_id?: string | null
          background_mode: string
          created_at?: string
          created_by: string
          filename?: string
          fit_mode: string
          format: string
          id?: string
          image_count: number
          include_69?: boolean
          orientation: string
          storage_path?: string | null
          workspace_id: string
        }
        Update: {
          app_id?: string | null
          background_mode?: string
          created_at?: string
          created_by?: string
          filename?: string
          fit_mode?: string
          format?: string
          id?: string
          image_count?: number
          include_69?: boolean
          orientation?: string
          storage_path?: string | null
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "export_sets_app_id_fkey"
            columns: ["app_id"]
            isOneToOne: false
            referencedRelation: "apps"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "export_sets_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      render_jobs: {
        Row: {
          attempts: number
          created_at: string
          error_code: string | null
          finished_at: string | null
          id: string
          kind: string
          lease_token: string | null
          lease_until: string | null
          payload: Json
          progress: Json | null
          request_key: string
          reservation_id: string | null
          result: Json | null
          state: string
          user_id: string
          workspace_id: string
        }
        Insert: {
          attempts?: number
          created_at?: string
          error_code?: string | null
          finished_at?: string | null
          id?: string
          kind: string
          lease_token?: string | null
          lease_until?: string | null
          payload: Json
          progress?: Json | null
          request_key: string
          reservation_id?: string | null
          result?: Json | null
          state?: string
          user_id: string
          workspace_id: string
        }
        Update: {
          attempts?: number
          created_at?: string
          error_code?: string | null
          finished_at?: string | null
          id?: string
          kind?: string
          lease_token?: string | null
          lease_until?: string | null
          payload?: Json
          progress?: Json | null
          request_key?: string
          reservation_id?: string | null
          result?: Json | null
          state?: string
          user_id?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "render_jobs_reservation_id_fkey"
            columns: ["reservation_id"]
            isOneToOne: false
            referencedRelation: "export_reservations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "render_jobs_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      review_links: {
        Row: {
          app_id: string | null
          client_name: string | null
          comment: string | null
          created_at: string
          created_by: string
          expires_at: string
          id: string
          orientation: string
          public_id: string
          render_job_id: string | null
          revoked_at: string | null
          set_name: string
          status: string
          updated_at: string
          workspace_id: string
        }
        Insert: {
          app_id?: string | null
          client_name?: string | null
          comment?: string | null
          created_at?: string
          created_by: string
          expires_at?: string
          id?: string
          orientation: string
          public_id: string
          render_job_id?: string | null
          revoked_at?: string | null
          set_name: string
          status?: string
          updated_at?: string
          workspace_id: string
        }
        Update: {
          app_id?: string | null
          client_name?: string | null
          comment?: string | null
          created_at?: string
          created_by?: string
          expires_at?: string
          id?: string
          orientation?: string
          public_id?: string
          render_job_id?: string | null
          revoked_at?: string | null
          set_name?: string
          status?: string
          updated_at?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "review_links_app_id_fkey"
            columns: ["app_id"]
            isOneToOne: false
            referencedRelation: "apps"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "review_links_render_job_id_fkey"
            columns: ["render_job_id"]
            isOneToOne: false
            referencedRelation: "render_jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "review_links_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      review_slides: {
        Row: {
          clone_label: string
          id: string
          inner_path: string
          outer_path: string
          review_id: string
          slide_index: number
        }
        Insert: {
          clone_label: string
          id?: string
          inner_path: string
          outer_path: string
          review_id: string
          slide_index: number
        }
        Update: {
          clone_label?: string
          id?: string
          inner_path?: string
          outer_path?: string
          review_id?: string
          slide_index?: number
        }
        Relationships: [
          {
            foreignKeyName: "review_slides_review_id_fkey"
            columns: ["review_id"]
            isOneToOne: false
            referencedRelation: "review_links"
            referencedColumns: ["id"]
          },
        ]
      }
      stripe_events: {
        Row: {
          id: string
          processed_at: string
          type: string
        }
        Insert: {
          id: string
          processed_at?: string
          type: string
        }
        Update: {
          id?: string
          processed_at?: string
          type?: string
        }
        Relationships: []
      }
      waitlist: {
        Row: {
          confirmed_at: string | null
          created_at: string
          email: string
          id: string
          last_sent_at: string
          locale: string
          token: string
          topic: string
        }
        Insert: {
          confirmed_at?: string | null
          created_at?: string
          email: string
          id?: string
          last_sent_at?: string
          locale?: string
          token: string
          topic: string
        }
        Update: {
          confirmed_at?: string | null
          created_at?: string
          email?: string
          id?: string
          last_sent_at?: string
          locale?: string
          token?: string
          topic?: string
        }
        Relationships: []
      }
      workspace_invitations: {
        Row: {
          accepted_at: string | null
          created_at: string
          email: string
          expires_at: string
          id: string
          invited_by: string
          revoked_at: string | null
          role: string
          token_hash: string
          workspace_id: string
        }
        Insert: {
          accepted_at?: string | null
          created_at?: string
          email: string
          expires_at?: string
          id?: string
          invited_by: string
          revoked_at?: string | null
          role?: string
          token_hash: string
          workspace_id: string
        }
        Update: {
          accepted_at?: string | null
          created_at?: string
          email?: string
          expires_at?: string
          id?: string
          invited_by?: string
          revoked_at?: string | null
          role?: string
          token_hash?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "workspace_invitations_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      workspace_members: {
        Row: {
          active: boolean
          created_at: string
          id: string
          role: string
          user_id: string
          workspace_id: string
        }
        Insert: {
          active?: boolean
          created_at?: string
          id?: string
          role: string
          user_id: string
          workspace_id: string
        }
        Update: {
          active?: boolean
          created_at?: string
          id?: string
          role?: string
          user_id?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "workspace_members_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      workspace_passes: {
        Row: {
          created_at: string
          days: number
          expires_at: string
          id: string
          stripe_checkout_session_id: string
          workspace_id: string
        }
        Insert: {
          created_at?: string
          days: number
          expires_at: string
          id?: string
          stripe_checkout_session_id: string
          workspace_id: string
        }
        Update: {
          created_at?: string
          days?: number
          expires_at?: string
          id?: string
          stripe_checkout_session_id?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "workspace_passes_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      workspaces: {
        Row: {
          client_slug: string | null
          created_at: string
          extra_app_packs: number
          free_exports_used: number
          id: string
          launch_offer_until: string | null
          manual_plan: string | null
          name: string
          pass_expires_at: string | null
          plan: string
          seats: number
          slug: string
          stripe_customer_id: string | null
          stripe_price_id: string | null
          stripe_subscription_id: string | null
          stripe_sync_version: number
          subscription_cancel_at_period_end: boolean
          subscription_period_end: string | null
          subscription_status: string | null
          updated_at: string
        }
        Insert: {
          client_slug?: string | null
          created_at?: string
          extra_app_packs?: number
          free_exports_used?: number
          id?: string
          launch_offer_until?: string | null
          manual_plan?: string | null
          name: string
          pass_expires_at?: string | null
          plan?: string
          seats?: number
          slug: string
          stripe_customer_id?: string | null
          stripe_price_id?: string | null
          stripe_subscription_id?: string | null
          stripe_sync_version?: number
          subscription_cancel_at_period_end?: boolean
          subscription_period_end?: string | null
          subscription_status?: string | null
          updated_at?: string
        }
        Update: {
          client_slug?: string | null
          created_at?: string
          extra_app_packs?: number
          free_exports_used?: number
          id?: string
          launch_offer_until?: string | null
          manual_plan?: string | null
          name?: string
          pass_expires_at?: string | null
          plan?: string
          seats?: number
          slug?: string
          stripe_customer_id?: string | null
          stripe_price_id?: string | null
          stripe_subscription_id?: string | null
          stripe_sync_version?: number
          subscription_cancel_at_period_end?: boolean
          subscription_period_end?: string | null
          subscription_status?: string | null
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      accept_workspace_invitation: {
        Args: {
          p_token_hash: string
          p_user_id: string
        }
        Returns: string
      }
      begin_checkout: {
        Args: {
          p_workspace_id: string
          p_kind: string
          p_return_path: string
        }
        Returns: Json
      }
      claim_asc_upload: {
        Args: never
        Returns: Json
      }
      claim_render: {
        Args: never
        Returns: Json
      }
      complete_render: {
        Args: {
          p_job: string
          p_lease: string
          p_result: Json
          p_export?: Json
          p_error?: string
        }
        Returns: undefined
      }
      consume_free_export: {
        Args: {
          p_workspace_id: string
          p_limit: number
        }
        Returns: number
      }
      create_workspace_invitation: {
        Args: {
          p_workspace_id: string
          p_user_id: string
          p_email: string
          p_token_hash: string
        }
        Returns: Json
      }
      enqueue_render: {
        Args: {
          p_user: string
          p_workspace: string
          p_kind: string
          p_key: string
          p_payload: Json
        }
        Returns: string
      }
      erase_account: {
        Args: {
          p_user_id: string
        }
        Returns: undefined
      }
      erase_current_user: {
        Args: never
        Returns: undefined
      }
      finish_export: {
        Args: {
          p_reservation: string
          p_export?: Json
        }
        Returns: undefined
      }
      get_review_payload: {
        Args: {
          pid: string
        }
        Returns: Json
      }
      grant_workspace_pass: {
        Args: {
          p_workspace_id: string
          p_session_id: string
          p_customer_id: string
          p_days: number
        }
        Returns: Json
      }
      heartbeat_render: {
        Args: {
          p_job: string
          p_lease: string
        }
        Returns: boolean
      }
      increment_daily_export: {
        Args: {
          p_workspace_id: string
        }
        Returns: number
      }
      refund_abandoned_exports: {
        Args: never
        Returns: number
      }
      refund_free_export: {
        Args: {
          p_workspace_id: string
        }
        Returns: number
      }
      report_render_progress: {
        Args: {
          p_job: string
          p_lease: string
          p_progress: Json
        }
        Returns: boolean
      }
      reserve_export: {
        Args: {
          p_workspace_id: string
          p_user_id: string
        }
        Returns: string
      }
      storage_cleanup_candidates: {
        Args: {
          p_user_id?: string
        }
        Returns: { bucket_id: string; name: string }[]
      }
      submit_review_decision: {
        Args: {
          pid: string
          new_status: string
          new_comment?: string
        }
        Returns: Json
      }
      workspace_member_emails: {
        Args: {
          p_workspace: string
        }
        Returns: { user_id: string; email: string }[]
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type PublicSchema = Database["public"]

export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"]
export type TablesInsert<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Insert"]
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Update"]
export type Enums<T extends keyof PublicSchema["Enums"]> = PublicSchema["Enums"][T]
export type CompositeTypes<T extends keyof PublicSchema["CompositeTypes"]> = PublicSchema["CompositeTypes"][T]
